language: node_js
cache:
  directories:
    - jest/tmp
    - node_modules
notifications:
  email: false
node_js:
  - "10"
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
